# Instala la extensión "REST Client" para poder usar este archivo  
## Guía resumida para usar la api de STRAPI

# para seleccionar solos los campos que deseamos obtener  =>  ?fields[0]=name&fields[1]=title&fields[2]=description..
# para obtener los campos que no se ven en la respuesta de la api como imagenes usar =>  ?populate=nombre_del_campo..
# para mostrar solo  los campos que necesitamos de los valores del populate =>  ?populate[nombre_campo][fields][0]=nombre_campo
# para filtrar por relacion => ?filters[nombre_relacion][campo][condicion]=valor_de_condicion

# GET http://localhost:1337/api/home?populate[datos_numericos][populate][icono][fields]=url
# GET http://localhost:1337/api/home?populate[datos_numericos][populate]=*
GET https://udhback.sistemasudh.com/api/home?fields[0]=locale&populate[imagenes_carousel][populate][imagen][fields]=url,name&populate[video_principal][populate][imagen_fondo][fields]=url,name&populate[caracteristicas][populate][icono][fields]=url,name&populate[datos_numericos][populate][icono][fields]=url,name&populate[paginas_amigas][populate][imagen][fields]=url,name&populate[noticias]=*&populate[nosotros][populate][imagen][fields]=url,name&populate[nosotros][populate][beneficios][populate][icono][fields]=url,name
Authorization: Bearer 163e4fba759de156c82fee67d03aba9f9a0d7e37ed7c0a704e099fce914d159b9ade2b775b921ad9b45a0fbd63cb0c07c9e3c6d0b871a5e771dd2072c9452964c1eeae3ea5ec10149a505be53db4bafff03fe760bf9b25c632d62b0d355432ab123f54c5ddde1bf162099903eaa31200ca28f7b4db874d082a8385db8d527534
 
###

GET https://udhback.sistemasudh.com/api/settings-page?fields[0]=nombreSitio&fields[1]=correoBoletin&fields[2]=link_login&fields[3]=numero_whatsapp&fields[4]=mensaje_whatsapp&fields[5]=locale&populate[favicon][fields]=url,name&populate[config_seo]=*&populate[contactos]=*&populate[redes_sociales][populate][icono][fields]=url,name&populate[logoudh][fields]=url,name&populate[logoudh_white][fields]=url,name&populate[enlaces_interes]=*
Authorization: Bearer 163e4fba759de156c82fee67d03aba9f9a0d7e37ed7c0a704e099fce914d159b9ade2b775b921ad9b45a0fbd63cb0c07c9e3c6d0b871a5e771dd2072c9452964c1eeae3ea5ec10149a505be53db4bafff03fe760bf9b25c632d62b0d355432ab123f54c5ddde1bf162099903eaa31200ca28f7b4db874d082a8385db8d527534